services:


################################################################################
  central-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: central-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14330:1433"
    volumes:
      - central_data:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

  client1-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client1-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14331:1433"
    volumes:
      - client1_data:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

  client2-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client2-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14332:1433"
    volumes:
      - client2_data:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

  client3-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client3-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14333:1433"
    volumes:
      - client3_data:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet
################################################################################

################################################################################
  syncserver:
    build: ../../SyncServer
    container_name: syncserver
    depends_on:
      - central-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ServerDb=Server=central-db,1433;Database=AdventureWorks;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
    ports:
      - "5201:8080"
    networks:
      - syncnet

  syncclient1:
    build: ../../SyncClient.Console
    container_name: syncclient1
    depends_on: 
      - client1-db
      - syncserver
    environment:
      - ConnectionStrings__ClientDb=Server=client1-db,1433;Database=AdventureWorks;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver:8080/api/sync
    networks:
      - syncnet

  syncclient2:
    build: ../../SyncClient.Console
    container_name: syncclient2
    depends_on:
      - client2-db
      - syncserver
    environment:
      - ConnectionStrings__ClientDb=Server=client2-db,1433;Database=AdventureWorks;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver:8080/api/sync
    networks:
      - syncnet

  syncclient3:
    build: ../../SyncClient.Console
    container_name: syncclient3
    depends_on:
      - client3-db
      - syncserver
    environment:
      - ConnectionStrings__ClientDb=Server=client3-db,1433;Database=AdventureWorks;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver:8080/api/sync
    networks:
      - syncnet



################################################################################








################################################################################
  init:
    image: mcr.microsoft.com/mssql-tools
    container_name: init-all
    depends_on:
      - central-db
      - client1-db
      - client2-db
      - client3-db
    environment:
      - SA_PASSWORD=Terya12345!
    volumes:
      - ./init:/init:ro
    # Esegui lo script senza chmod e converti CRLF -> LF in /tmp
    entrypoint: ["bash","-lc","tr -d '\\r' </init/init.sh >/tmp/init.sh && bash /tmp/init.sh"]
    networks:
      - syncnet
################################################################################



################################################################################
networks:
  syncnet: {}
################################################################################





################################################################################
volumes:
  central_data: {}
  client1_data: {}
  client2_data: {}
  client3_data: {}
################################################################################