services:

#-----------------------------------------------------------#
  central-db-TDS:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: central-db-TDS
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14330:1433"
    volumes:
      - central_data_staging:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet


  client1-db-TDS:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client1-db-TDS
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14331:1433"
    volumes:
      - client1_data_staging:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

  client2-db-TDS:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client2-db-TDS
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14332:1433"
    volumes:
      - client2_data_staging:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

  client3-db-TDS:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: client3-db-TDS
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Terya12345!
      - MSSQL_PID=Express
    ports:
      - "14333:1433"
    volumes:
      - client3_data_staging:/var/opt/mssql
      - ./init:/var/opt/mssql/backup
    networks:
      - syncnet

#-----------------------------------------------------------#

  init:
    image: mcr.microsoft.com/mssql-tools
    container_name: init-TDS
    depends_on:
      - central-db-TDS
      - client1-db-TDS
      - client2-db-TDS
      - client3-db-TDS
    environment:
      - SA_PASSWORD=Terya12345!
    volumes:
      - ./init:/init:ro
    entrypoint: ["bash","-lc","tr -d '\r' </init/init.sh >/tmp/init.sh && bash /tmp/init.sh"]
    networks:
      - syncnet

  syncserver-TDS:
    build: ../../SyncServer
    image: syncserver-tds:latest
    container_name: syncserver-TDS
    depends_on:
      - central-db-TDS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ServerDb=Server=central-db-TDS,1433;Database=TerraDiSiena;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
    ports:
      - "5201:8080"
    networks:
      - syncnet

  syncclient1-TDS:
    build: ../../SyncClient
    image: syncclient1-tds:latest
    container_name: syncclient1-TDS
    depends_on:
      - client1-db-TDS
      - syncserver-TDS
    environment:
      - ConnectionStrings__ClientDb=Server=client1-db-TDS,1433;Database=TerraDiSiena;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver-TDS:8080/api/sync
    networks:
      - syncnet

  syncclient2-TDS:
    build: ../../SyncClient
    image: syncclient2-tds:latest
    container_name: syncclient2-TDS
    depends_on:
      - client2-db-TDS
      - syncserver-TDS
    environment:
      - ConnectionStrings__ClientDb=Server=client2-db-TDS,1433;Database=TerraDiSiena;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver-TDS:8080/api/sync
    networks:
      - syncnet

  syncclient3-TDS:
    build: ../../SyncClient
    image: syncclient3-tds:latest
    container_name: syncclient3-TDS
    depends_on:
      - client3-db-TDS
      - syncserver-TDS
    environment:
      - ConnectionStrings__ClientDb=Server=client3-db-TDS,1433;Database=TerraDiSiena;User ID=sa;Password=Terya12345!;Encrypt=True;TrustServerCertificate=True
      - Sync__ServiceUrl=http://syncserver-TDS:8080/api/sync
    networks:
      - syncnet






networks:
  syncnet: {}



volumes:
  central_data_staging: {}
  client1_data_staging: {}
  client2_data_staging: {}
  client3_data_staging: {}